### ISSUE TITLE
Results should map to events in someway

### ISSUE THREAD

**Issue by brentdur** [TechAtNYU/text-feedback#2]
Perhaps by just assuming the responses are to the most recent event in the api? Unless you can think of a better way

**Comment by css459** [comment]
Maybe we can set the name by texting a special prelude and event name? It will then just name the JSON file that. Also, maybe we can have a secure way to stop the server remotely when the event is over. Then I don't think we'd need a supervisor file right? Unless you want this always on, then ngrok is not a good solution.

**Comment by brentdur** [comment]
A.) Not sure about whether it's gonna be on forever, but it will be on for at least the duration of this startup week
B.) We can only have one number, meaning we can only take in responses for one event at a time (we don't want ppl to have to text the event name, etc). So let's just say the server changes to a new event (writes a new json file) 15 (or 30?) minutes after an event starts and continues to write to that until a new event starts. This will require some polling (every X minutes) from this server to the api but I think it's worth it to avoid the inevitable "someone forget to text the special event prelude text and now all the feedback is lumped together" case

**Comment by css459** [comment]
Ah I see, that's a good point. I could make it hook into the intranet and track the current event against the current time, but that would require more work. When would be the deadline you think for something like that?

**Comment by brentdur** [comment]
Eh. Next Monday?

**Comment by css459** [comment]
Cool. I'll have it done far before then 👍

**Comment by css459** [comment]
I’m sorry Brenton, I’ve been so busy with midterms and studying that I totally forgot to handle the bug here. Is there any quick-fix solution that you think would work? I can try to work on this tonight. 

Thanks,

	Cole

Cole Smith
New York University | 2019
Computer Science | Economics
Email | css@nyu.edu
Phone | 727-417-7159
