### ISSUE TITLE
Fix Twilio Errors

### ISSUE THREAD

**Issue by brentdur** [TechAtNYU/text-feedback#3]
https://www.twilio.com/console/dev-tools/debugger/NOe5c25ead805f91e6e90e8f79fbffd969

Seems to be related to the server not giving a response? It's minor in the grand scheme of things but probably better to adhere to what Twilio expects

**Comment by css459** [comment]
Those 502 Errors I think were old errors from me testing. It shouldn't happen if you use ngrok and set the URL from ngrok on Twilio as suggested.
